# Generated by Django 4.2.1 on 2023-05-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneDomainPredictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('predicted_class', models.CharField(max_length=255)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Domain Predictor',
                'verbose_name_plural': 'Domain Predictors',
            },
        ),
    ]
